# Rappresentazione basilare di come avviene la selezione dell'hop successivo

I nomi delel variabili corrispondono il piu' possibile alla realta'

## librerie

In [38]:
import numpy as np

## bozza di simulazione con tutte le informazioni che servono per la selezione dell'hop

In [39]:
ndrones = 10
opt_neighbors = [(1, 0), (2, 3), (4, 5)] # (id hello packet, id drone che ha genrerato hello packet)

id dei vicini

In [40]:
vicini = [helloPacket[1] for helloPacket in opt_neighbors]

In [41]:
vicini_ID = vicini # perche' e' piu' semplice simulare il funzionamento astratto

determino altri parametri per la simulazione

In [42]:
k_weight = np.random.rand(len(vicini_ID)) # calcolo i valori in modo random
k_weight

array([0.63096156, 0.51467101, 0.03546624])

In [43]:
velocita_attuali = np.random.rand(len(vicini_ID))
velocita_attuali

array([0.14310094, 0.89028414, 0.23524848])

In [44]:
all_requested_velocities = np.random.rand(len(vicini_ID))
all_requested_velocities

array([0.21346738, 0.81509485, 0.89126942])

genero qtable

In [45]:
qtable = np.random.rand(ndrones)
qtable

array([0.94148555, 0.91869866, 0.6036175 , 0.62986327, 0.16151643,
       0.01003478, 0.29167588, 0.54380914, 0.75203415, 0.44332896])



---

# avvio il meccanismo di selezione

effettuo selezione sulla qtable

In [46]:
q_table_selection = qtable[vicini_ID]
q_table_selection

array([0.94148555, 0.62986327, 0.01003478])

ottengo i qvalue pesati

In [47]:
q_value_pesati = np.multiply(q_table_selection, k_weight)
q_value_pesati

array([5.94041190e-01, 3.24172368e-01, 3.55895818e-04])

determino quali sono gli hop selezionabili

In [48]:
hop_selezionabili = np.where(velocita_attuali >= all_requested_velocities)[0] # ottieni indici
hop_selezionabili

array([1])

In [49]:
hop_candidati = np.asarray(vicini_ID)[hop_selezionabili] # seleziona elementi che si trovano negli indici selezionati
hop_candidati

array([3])

maschera

In [50]:
maschera = np.ones(shape=(len(vicini_ID)), dtype = bool) # crea maschera di tutti true
maschera

array([ True,  True,  True])

In [51]:
maschera[hop_selezionabili] = False # false per gli elementi che voglio ottenere mediante la maschera
maschera

array([ True, False,  True])

applica la maschera ai qvalue

In [52]:
q_value_mascherati = np.ma.masked_array(q_value_pesati, maschera) # ottieni elemnti applicando la maschera
q_value_mascherati

masked_array(data=[--, 0.32417236793059523, --],
             mask=[ True, False,  True],
       fill_value=1e+20)

seleziona hop

In [53]:
hop_selezionato_indice = np.argmax(q_value_mascherati) # ottnei hop successivo
hop_selezionato_indice

1

In [54]:
hop_selezionato_valore = np.max(q_value_mascherati)
hop_selezionato_valore

0.32417236793059523

In [55]:
hop_selezionato = vicini[hop_selezionato_indice]
hop_selezionato

3